version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ans_database
    restart: always
    environment:
      POSTGRES_DB: ans_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./downloads:/docker-data


volumes:
  db_data:
